### ISSUE TITLE
"Permission Denied" while running "./setup.sh" Mac user

### ISSUE THREAD

**Issue by raggnar** [shantnu/Python-Awesome-Job#3]
Hi Shantnu,

I have the error message : "permission denied" while i am running "./setup.sh" on my Mac . Can you please advised

Thanks

**Comment by raggnar** [comment]
chmod the shell command using "chmod +x setup.sh" and it worked a bit.

now i have the error message below

ERROR: File or directory already exists: /root/miniconda3
./setup.sh: line 17: /home/vagrant/miniconda3/bin/conda: No such file or directory
./setup.sh: line 18: /home/vagrant/miniconda3/bin/pip: No such file or directory

what should i do now?

Thanks

**Comment by raggnar** [comment]
all good i was running the command as root (sudo su) user.

after changing the sh to x mode ran the command as main user and it is all working now

**Comment by shantnu** [comment]
Cool, you solved your own problem. That's the best sort of help :)
